# Generated by Django 5.1.7 on 2025-03-12 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_recordatorio',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 21, 56, 14, 842799, tzinfo=datetime.timezone.utc)),
        ),
    ]
